# Generated by Django 5.0.4 on 2024-05-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rabbit_app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
